-- AlterEnum: Add new building types
ALTER TYPE "BuildingType" ADD VALUE IF NOT EXISTS 'HOSPITAL';
ALTER TYPE "BuildingType" ADD VALUE IF NOT EXISTS 'WALL';
ALTER TYPE "BuildingType" ADD VALUE IF NOT EXISTS 'EMBASSY';
ALTER TYPE "BuildingType" ADD VALUE IF NOT EXISTS 'FORGE';

-- AlterEnum: Add new research types
ALTER TYPE "ResearchType" ADD VALUE IF NOT EXISTS 'METALLURGY';
ALTER TYPE "ResearchType" ADD VALUE IF NOT EXISTS 'MEDICINE';
ALTER TYPE "ResearchType" ADD VALUE IF NOT EXISTS 'CAVALRY_TACTICS';
ALTER TYPE "ResearchType" ADD VALUE IF NOT EXISTS 'CITY_PLANNING';
ALTER TYPE "ResearchType" ADD VALUE IF NOT EXISTS 'ARCHERY';

-- AlterTable: Add wounded troop fields to City
ALTER TABLE "City" ADD COLUMN IF NOT EXISTS "woundedInfantry" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "City" ADD COLUMN IF NOT EXISTS "woundedArcher" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "City" ADD COLUMN IF NOT EXISTS "woundedCavalry" INTEGER NOT NULL DEFAULT 0;
